# Generated by Django 3.2.3 on 2021-05-20 21:32

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('approval', models.CharField(blank=True, choices=[('VERIFIED', 'VERIFIED'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], default='PENDING', max_length=15, null=True)),
                ('plan', models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('DIAMOND', 'DIAMOND')], default='DAILY', max_length=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='min-amount: $50, max-amount: $100000', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('50.00')), django.core.validators.MaxValueValidator(Decimal('1000000.00'))], verbose_name='Deposited Amount')),
                ('deposited', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='RecoverFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('approval', models.CharField(blank=True, choices=[('VERIFIED', 'VERIFIED'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], default='PENDING', max_length=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='min-amount: $100, max-amount: $100000', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('100.00')), django.core.validators.MaxValueValidator(Decimal('1000000.00'))], verbose_name='Lost Amount')),
                ('wallet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_broker', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('resolved_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Fund Recovery',
                'verbose_name_plural': 'Fund Recoveries',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('issue', models.TextField(verbose_name='Type your complains here')),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Supports',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('approval', models.CharField(blank=True, choices=[('VERIFIED', 'VERIFIED'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], default='PENDING', max_length=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='min-amount: $100, max-amount: $100000', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('100.00')), django.core.validators.MaxValueValidator(Decimal('1000000.00'))], verbose_name='Withdrawal Amount')),
                ('wallet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('withdrawn', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-modified'],
            },
        ),
    ]
