# Generated by Django 3.2.3 on 2021-08-03 04:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverfunds',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='min-amount: $100, max-amount: $100000000', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('100.00')), django.core.validators.MaxValueValidator(Decimal('100000000.00'))], verbose_name='Lost Amount'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='min-amount: $100, max-amount: $100000000', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('100.00')), django.core.validators.MaxValueValidator(Decimal('100000000.00'))], verbose_name='Withdrawal Amount'),
        ),
    ]
