# Generated by Django 3.2.3 on 2021-05-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='issue',
            field=models.TextField(verbose_name='Type your complains here'),
        ),
    ]
