# Generated by Django 3.2.3 on 2021-05-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_support_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='plan',
            field=models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('DIAMOND', 'DIAMOND')], default='DAILY', max_length=15, null=True),
        ),
    ]
