# Generated by Django 3.2.3 on 2021-05-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210531_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='code',
            field=models.CharField(blank=True, default='5ba4b5e', max_length=7, null=True),
        ),
    ]
