# Generated by Django 3.2.3 on 2021-05-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='active',
            field=models.BooleanField(default=False, verbose_name='FAQ Active?'),
        ),
    ]
